#include <iostream>
using namespace std;
int main()
{
	int a;
	while (cin >> a)
	{
		if (a == 0)
			cout << "zero" << endl;
		else if (a == 1)
			cout << "one" << endl;
		else if (a == 2)
			cout << "two" << endl;
		else if (a == 3)
			cout << "three" << endl;
		else if (a == 4)
			cout << "four" << endl;
		else if (a == 5)
			cout << "five" << endl;
		else if (a == 6)
			cout << "six" << endl;
		else if (a == 7)
			cout << "seven" << endl;
		else if (a == 8)
			cout << "eight" << endl;
		else if (a == 9)
			cout << "nine" << endl;
		else if (a == 10)
			cout << "ten" << endl;
		else if (a == 11)
			cout << "eleven" << endl;
		else if (a == 12)
			cout << "twelve" << endl;
		else if (a == 13)
			cout << "thirteen" << endl;
		else if (a == 14)
			cout << "fourteen" << endl;
		else if (a == 15)
			cout << "fifteen" << endl;
		else if (a == 16)
			cout << "sixteen" << endl;
		else if (a == 17)
			cout << "seventeen" << endl;
		else if (a == 18)
			cout << "eighteen" << endl;
		else if (a == 19)
			cout << "nineteen" << endl;
		else if (a == 20)
			cout << "twenty" << endl;
		else if (a == 21)
			cout << "twenty-one" << endl;
		else if (a == 22)
			cout << "twenty-two" << endl;
		else if (a == 23)
			cout << "twenty=three" << endl;
		else if (a == 24)
			cout << "twenty-four" << endl;
		else if (a == 25)
			cout << "twenty-five" << endl;
		else if (a == 26)
			cout << "twenty-six" << endl;
		else if (a == 27)
			cout << "twenty-seven" << endl;
		else if (a == 28)
			cout << "twenty-eight" << endl;
		else if (a == 29)
			cout << "twenty-nine" << endl;
		else if (a == 30)
			cout << "thirty" << endl;
		else if (a == 31)
			cout << "thirty-one" << endl;
		else if (a == 32)
			cout << "thirty-two" << endl;
		else if (a == 33)
			cout << "thirty-three" << endl;
		else if (a == 34)
			cout << "thirty-four" << endl;
		else if (a == 35)
			cout << "thirty-five" << endl;
		else if (a == 36)
			cout << "thirty-six" << endl;
		else if (a == 37)
			cout << "thirty-seven" << endl;
		else if (a == 38)
			cout << "thirty-eight" << endl;
		else if (a == 39)
			cout << "thirty=nine" << endl;
		else if (a == 40)
			cout << "forty" << endl;
		else if (a == 41)
			cout << "forty-one" << endl;
		else if (a == 42)
			cout << "forty-two" << endl;
		else if (a == 43)
			cout << "forty-three" << endl;
		else if (a == 44)
			cout << "forty-four" << endl;
		else if (a == 45)
			cout << "forty-five" << endl;
		else if (a == 46)
			cout << "forty-six" << endl;
		else if (a == 47)
			cout << "forty-seven" << endl;
		else if (a == 48)
			cout << "forty-eight" << endl;
		else if (a == 49)
			cout << "forty-nine" << endl;
		else if (a == 50)
			cout << "fifty" << endl;
		else if (a == 51)
			cout << "fifty-one" << endl;
		else if (a == 52)
			cout << "fifty-two" << endl;
		else if (a == 53)
			cout << "fifty-three" << endl;
		else if (a == 54)
			cout << "fifty-four" << endl;
		else if (a == 55)
			cout << "fifty-five" << endl;
		else if (a == 56)
			cout << "fifty-six" << endl;
		else if (a == 57)
			cout << "fifty-seven" << endl;
		else if (a == 58)
			cout << "fifty-eight" << endl;
		else if (a == 59)
			cout << "fifty-nine" << endl;
		else if (a == 60)
			cout << "sixty" << endl;
		else if (a == 61)
			cout << "sixty-one" << endl;
		else if (a == 62)
			cout << "sixty-two" << endl;
		else if (a == 63)
			cout << "sixty-three" << endl;
		else if (a == 64)
			cout << "sixty-four" << endl;
		else if (a == 65)
			cout << "sixty-five" << endl;
		else if (a == 66)
			cout << "sixty-six" << endl;
		else if (a == 67)
			cout << "sixty-seven" << endl;
		else if (a == 68)
			cout << "sixty-eight" << endl;
		else if (a == 69)
			cout << "sixty-nine" << endl;
		else if (a == 70)
			cout << "seventy" << endl;
		else if (a == 71)
			cout << "seventy-one" << endl;
		else if (a == 72)
			cout << "seventy-two" << endl;
		else if (a == 73)
			cout << "seventy-three" << endl;
		else if (a == 74)
			cout << "seventy-four" << endl;
		else if (a == 75)
			cout << "seventy-five" << endl;
		else if (a == 76)
			cout << "seventy-six" << endl;
		else if (a == 77)
			cout << "seventy-seven" << endl;
		else if (a == 78)
			cout << "seventy-eight" << endl;
		else if (a == 79)
			cout << "seventy-nine" << endl;
		else if (a == 80)
			cout << "eighty" << endl;
		else if (a == 81)
			cout << "eighty-one" << endl;
		else if (a == 82)
			cout << "eighty-two" << endl;
		else if (a == 83)
			cout << "eighty-three" << endl;
		else if (a == 84)
			cout << "eighty-four" << endl;
		else if (a == 85)
			cout << "eighty-five" << endl;
		else if (a == 86)
			cout << "eighty-six" << endl;
		else if (a == 87)
			cout << "eighty-seven" << endl;
		else if (a == 88)
			cout << "eighty-eight" << endl;
		else if (a == 89)
			cout << "eighty-nine" << endl;
		else if (a == 90)
			cout << "ninety" << endl;
		else if (a == 91)
			cout << "ninety-one" << endl;
		else if (a == 92)
			cout << "ninety-two" << endl;
		else if (a == 93)
			cout << "ninety-three" << endl;
		else if (a == 94)
			cout << "ninety-four" << endl;
		else if (a == 95)
			cout << "ninety-five" << endl;
		else if (a == 96)
			cout << "ninety-six" << endl;
		else if (a == 97)
			cout << "ninety-seven" << endl;
		else if (a == 98)
			cout << "ninety-eight" << endl;
		else if (a == 99)
			cout << "ninety-nine" << endl;
	}
	return 0;
}